const rules = {
  waitMessage: "Please wait,system processing your request.",
  email: "Please enter email.",
  actualStartDate: "Please actual start date.",
  actualEndDate: "Please actual end date.",
  receiptDate: "Select receipt date.",
  name: "Please enter name.",
  darpanId: "Please enter Darpan ID.",
  validDarpan: "Please enter valid Darpan ID.",
  darpanLen: "Please enter 15 digit valid Darpan ID.",
  panNo: "Please enter PAN number.",
  panLen: "Please enter 10 digit PAN number.",
  validPan: "Please enter valid PAN number.",
  details: "Please enter detail.",
  mobile: "Please enter mobile.",
  udisecode: "Please enter udise code.",
  upload_year: "Please select year.",
  validMobile: "Please enter 10 digit.",
  //validNriMobile              :   "Please enter minimum 8 & maximum 14 digits.",
  validUdiseLen: "Please enter 11 digit udise code.",
  maxDuration: "Cannot enter more than 50 days.",
  validUdiseCode: "Please enter valid udise code.",
  otp: "Please enter OTP.",
  validOtp: "Please enter 6 digit OTP.",
  validEmail: "Please enter valid email.",
  password: "Please enter password.",
  passwordStrong: "Password not strong. ",
  oldPassword: "Please enter old password.",
  newPassword: "Please enter new password.",
  confirmPassword: "Please enter confirm password.",
  bothPasswrod: "Both passwords are not matched.",
  passwordLength: "Minimum length 8 characters.",
  captcha: "Captcha required.",
  captchaLength: "Must have 6 character.",
  onlyAlpha: "Only character value allowed.",
  onlyNumeric: "Only numeric value allowed.",
  feedback: "Please select feedback.",
  stateName: "Please enter state name.",
  districtName: "Please enter district name.",
  selectStateName: "Please select state name.",
  selectDIETName: "Please select DIET name.",
  selectVtypeName: "Please select volunteer type.",
  selectActivtyName: "Please select activity name.",
  selectClassName: "Please select class name.",
  selectMaintenenceName: "Please select maintenance",
  selectGenderName: "Please select gender.",
  selectspecializationsName: "Please select specialization.",
  selectDuration: "Please enter duration.",
  selectImpactedStudent: "Please enter impacted student.",
  quantity: "Please enter quantity.",
  selectStartDate: "Please select date.",
  meetingDate: "Please select meeting date.",
  selectLastDate: "Please select date.",
  selectCountry: "Please select country.",
  details: "Please enter details.",
  message: "Please enter message.",
  subject: "Please enter subject.",
  Qty: "Please enter qty.",
  approveQty: "Please enter approve qty.",
  selectSpecializationName: "Please select specialization name.",
  selectDistrictName: "Please select district name.",
  selectBlockName: "Please select block  name.",
  selectDesignationName: "Please enter designation name.",
  selectRoleName: "Please select role name.",
  designationName: "Please enter designation name.",
  slelectCategory: "Please select category.",
  slelectColser: "Please select close reason.",
  deliveyStatus: "Select delivery status.",
  remark: "Please enter school declaration.",
  comment: "Please enter your remark.",
  minSize: "Please enter at least 20 words.",
  maxSize: "Maximum 50 words allowed.",
  maxMinSize: "Minimum 20 & Maximum 50 words.",
  file: "Please select a document.",
  startdate: "Please enter start date.",
  enddate: "Please enter end date.",
  selectAsset: "Please enter asset.",
  sub_asset: "Please enter sub_asset.",
  unit: "Please enter unit.",
  title: "Please enter Title",
  typecode: "Please enter Type code",
  description: "Please enter Description",
  status: "Please select status",
  stateid: "Please enter State",
  districtid: "Please enter District",
  blockid: "Please enter Block",
  linktoschool: "Please enter Link to school ID",
  udise_code: "Please enter Udise ID",
  file_type: "Select File Type",
  document_type: "Select Document Type",
  master_type_detail_id: "Select Type detail ",
  comment: "Please enter comment.",
  commentMinSize: "Please enter at least 3 words.",
  user_mobile: "Please enter Self Mobile Number",
  ref_user_mobile: "Please enter Self Mobile Number",
};

export default rules;
